### ISSUE TITLE
抓虫 第6章 文本和字体 Extracting Text from a Document 小节（原书 epub 版 53 页）

### ISSUE THREAD

**Issue by kvii** [pdf-books-cn/PDF-Explained#17]
原文

> “It is customary to include enough information in a file’s font
    dictionaries to allow the actual character identities (rather than just
    the glyphs) to be retrieved. This is important to allow users to search
    and copy text from PDF viewing applications like Adobe Reader. **In** can also
    be used, in a more limited capacity, to allow edits to be made to the
    textual content of a document.”

摘录来自
PDF Explained
John Whitington
此材料可能受版权保护。

译文

> 习惯上在文件的字体词典中包含足够的信息，以允许检索实际的字符标识（而不仅仅是字形）。 这对于允许用户从PDF查看应用程序（如Adobe Reader）中搜索和复制文本非常重要。**In**还可以以更有限的容量使用，以允许对文档的文本内容进行编辑。

这里的 "**In** can also be used" 被翻译成了 "**In**还可以以更有限..."。我个人觉得这里可能是原文写错了，把 "It" 写成 "In" 了。如果换成 "It" 的话这个句子就通顺了。

**Comment by zxyle** [comment]
已修正
