### ISSUE TITLE
将图片换成中文的图片

### ISSUE THREAD

**Issue by zxyle** [pdf-books-cn/PDF-Explained#2]

**Comment by gomggx** [comment]
我可以帮忙翻译。怎么提交译稿呢

**Comment by zxyle** [comment]
我现在发现图片上的专用的英文术语， 不翻译也没什么问题。
提交译稿步骤: 1.fork这个仓库，2. 在fork出来的仓库进行更改 3. 提交pull request

**Comment by gomggx** [comment]
是的，很难找到合适的中文词语与英文相对应。有空我翻译下提交对照稿吧
