### ISSUE TITLE
第三章翻译问题

### ISSUE THREAD

**Issue by qmhball** [pdf-books-cn/PDF-Explained#7]
## Header 部分
>The percent sign indicates a comment。 
> 目前翻译：百分号表示另一个标题行
正确译文应该是：百分号表示注释。

## Body部分
> The file body consists of a sequence of objects, each preceded by an object number, generation number, and the obj keyword on one line, and followed by the endobj keyword on another.
> 这样翻译比如容易懂：文件正文由一系列对象组成，每个对象前会有单独的一行，该行包括一个对象编号，一个世代号以及关键字obj。紧跟象之后的是endobj关键字，它同样独占一行。

**Comment by zxyle** [comment]
可以提交一个PR
